version: "3.6"

services:
  influxdb:
    image: influxdb:alpine
    environment:
      - INFLUXDB_DB=crypto
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_REPORTING_DISABLED=true
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - 8086:8086

volumes:
  influxdb-data: